# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-15 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.CreateModel(
            name='LeaderBoardBoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RunescapeEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('_image', models.CharField(max_length=100)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.CreateModel(
            name='BingoCard',
            fields=[
                ('gamecard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.GameCard')),
                ('square1_proof', models.CharField(max_length=500, null=True)),
                ('square2_proof', models.CharField(max_length=500, null=True)),
                ('square3_proof', models.CharField(max_length=500, null=True)),
                ('square4_proof', models.CharField(max_length=500, null=True)),
                ('square5_proof', models.CharField(max_length=500, null=True)),
                ('square6_proof', models.CharField(max_length=500, null=True)),
                ('square7_proof', models.CharField(max_length=500, null=True)),
                ('square8_proof', models.CharField(max_length=500, null=True)),
                ('square9_proof', models.CharField(max_length=500, null=True)),
                ('square10_proof', models.CharField(max_length=500, null=True)),
                ('square11_proof', models.CharField(max_length=500, null=True)),
                ('square12_proof', models.CharField(max_length=500, null=True)),
                ('square13_proof', models.CharField(max_length=500, null=True)),
                ('square14_proof', models.CharField(max_length=500, null=True)),
                ('square15_proof', models.CharField(max_length=500, null=True)),
                ('square16_proof', models.CharField(max_length=500, null=True)),
                ('square17_proof', models.CharField(max_length=500, null=True)),
                ('square18_proof', models.CharField(max_length=500, null=True)),
                ('square19_proof', models.CharField(max_length=500, null=True)),
                ('square20_proof', models.CharField(max_length=500, null=True)),
                ('square21_proof', models.CharField(max_length=500, null=True)),
                ('square22_proof', models.CharField(max_length=500, null=True)),
                ('square23_proof', models.CharField(max_length=500, null=True)),
                ('square24_proof', models.CharField(max_length=500, null=True)),
                ('square25_proof', models.CharField(max_length=500, null=True)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('games.gamecard',),
        ),
        migrations.CreateModel(
            name='BingoCompetition',
            fields=[
                ('competition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.Competition')),
                ('type', models.CharField(choices=[('ITEMS', 'Items'), ('BOSSES', 'Bosses'), ('BOTH', 'Items and Bosses')], max_length=100)),
                ('wilderness', models.BooleanField()),
                ('slayer', models.BooleanField()),
                ('free_space', models.BooleanField()),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('games.competition',),
        ),
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('runescapeentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.RunescapeEntity')),
                ('wilderness', models.BooleanField()),
                ('slayer', models.BooleanField()),
                ('slayer_level', models.IntegerField()),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('games.runescapeentity',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('runescapeentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.RunescapeEntity')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('games.runescapeentity',),
        ),
        migrations.CreateModel(
            name='LeaderBoardCard',
            fields=[
                ('gamecard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.GameCard')),
                ('proof', models.CharField(max_length=256)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Drop')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('games.gamecard',),
        ),
        migrations.CreateModel(
            name='LeaderBoardCompetition',
            fields=[
                ('competition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.Competition')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('games.competition',),
        ),
        migrations.AddField(
            model_name='runescapeentity',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_games.runescapeentity_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='gamecard',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_cards', to='games.Competition'),
        ),
        migrations.AddField(
            model_name='gamecard',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_games.gamecard_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='competition',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_games.competition_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='competition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaderboardboss',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Boss'),
        ),
        migrations.AddField(
            model_name='leaderboardboss',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bosses', to='games.LeaderBoardCompetition'),
        ),
        migrations.AddField(
            model_name='drop',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Boss'),
        ),
        migrations.AddField(
            model_name='drop',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Item'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square10_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square10_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square11_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square11_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square12_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square12_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square13_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square13_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square14_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square14_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square15_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square15_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square16_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square16_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square17_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square17_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square18_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square18_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square19_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square19_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square1_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square1_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square20_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square20_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square21_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square21_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square22_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square22_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square23_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square23_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square24_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square24_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square25_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square25_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square2_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square2_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square3_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square3_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square4_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square4_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square5_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square5_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square6_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square6_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square7_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square7_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square8_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square8_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square9_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square9_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.RunescapeEntity'),
        ),
    ]
