# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-14 20:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('_image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GameCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('_image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BingoCard',
            fields=[
                ('gamecard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.GameCard')),
            ],
            bases=('games.gamecard',),
        ),
        migrations.AddField(
            model_name='gamecard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drop',
            name='main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Item'),
        ),
        migrations.AddField(
            model_name='drop',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Boss'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square13',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square14',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square15',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square16',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square17',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square18',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square19',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square20',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square21',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square22',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square23',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square24',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square25',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop'),
        ),
    ]
