# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecard',
            name='user_name',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
