# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BingoCard',
            fields=[
                ('gamecard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.GameCard')),
                ('square1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square14', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square15', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square16', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square17', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square18', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square19', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square20', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square21', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square22', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square23', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square24', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square25', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
                ('square9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Drop')),
            ],
            bases=('games.gamecard',),
        ),
        migrations.AddField(
            model_name='gamecard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
