# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoardDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bosses', to='games.LeaderBoardCompetition')),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Drop')),
            ],
        ),
        migrations.RemoveField(
            model_name='leaderboardboss',
            name='boss',
        ),
        migrations.RemoveField(
            model_name='leaderboardboss',
            name='competition',
        ),
        migrations.DeleteModel(
            name='LeaderBoardBoss',
        ),
    ]
