# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-25 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('games', '0002_gamecard_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecard',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_games.gamecard_set+', to='contenttypes.ContentType'),
        ),
    ]
