# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-19 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190219_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardcard',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
