# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-19 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_leaderboardcard_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboarddrop',
            name='drop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='games.Drop'),
        ),
    ]
