# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-25 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamecard_polymorphic_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingocard',
            name='square10_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square11_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square12_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square13_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square14_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square15_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square16_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square17_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square18_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square19_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square1_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square20_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square21_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square22_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square23_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square24_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square25_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square2_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square3_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square4_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square5_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square6_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square7_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square8_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='square9_proof',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
