# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-19 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20190219_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardcompetition',
            name='configured',
            field=models.BooleanField(default=False),
        ),
    ]
